# Installation

In [ ]:
!pip install --upgrade pip
!pip install tensorflow

# Imports

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


## 1. Listing all the datatypes supported in ternsorflow

Tensors are multi-dimensional arrays with a uniform type (called a dtype). You can see all supported dtypes at tf.dtypes.DType.
[tf.dtypes](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType)

### 2. Basic Tensors


In [8]:
# rank_0_tensor

a = tf.constant(4)
print(a)

tf.Tensor(4, shape=(), dtype=int32)


In [14]:
# rank_1_tesnsor (vector)
vector = tf.constant([2,3,4,5,6], dtype = tf.int64)
print(vector)

tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int64)


In [15]:
# rank_2_tensor (Matrix)

matrix = tf.constant([
    [2, 4, 6],
    [3, 6, 9],
    [4, 8, 12],
    [5, 10, 15]
])

print(matrix)

tf.Tensor(
[[ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]], shape=(4, 3), dtype=int32)


In [23]:
# Creating a 3 dimensional tensor from of float numbers.
# Note that [1.] will tell tensorflow that we want the whole tensor to have a float dtpye
matrix3d = tf.constant([
    [
        [1., 2,3,4],
        [2, 4, 6, 8],
        [3, 6, 9, 12]
    ],
      [
          [1*-1, 2*-1,3*-1,4*-1],
        [2*-1, 4*-1, 6*-1, 8*-1],
        [3*-1, 6*-1, 9*-1, 12*-1]
      ]
])

matrix3d

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[  1.,   2.,   3.,   4.],
        [  2.,   4.,   6.,   8.],
        [  3.,   6.,   9.,  12.]],

       [[ -1.,  -2.,  -3.,  -4.],
        [ -2.,  -4.,  -6.,  -8.],
        [ -3.,  -6.,  -9., -12.]]], dtype=float32)>

### 3. Converting tensors to numpy Array
* There are two ways of converting a tensor to a numpy array
    * numpy.array(tensor)
    * tensor.numpy()
    

In [27]:
# first method
tensor = tf.Variable([2, 3, 4, 5])
numpy_array = np.array(tensor)
numpy_array

# second method

numpy_array = tensor.numpy()
numpy_array

array([2, 3, 4, 5])

## Mathematics Operations on Tensors
* We can perform a lot of mathemetical operations on tensors
    * [Documentation](https://www.tensorflow.org/api_docs/python/tf/math)

### Functions

In [31]:
#  Let's say we have these two tensors

a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]])
c = tf.constant([-2., -8, 9, 6, -19])

### 1. tf.add()
* performs additions on tensors


In [35]:
# Method 1
print(a+b) # add element wise
# Method 2
print(tf.add(a, b))

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


### 2. tf.matmul()
* performs matrix multiplication


In [37]:
# Matrix Multiplication
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]])>

### 3. tf.multipy()
* performs multiplications on sensors


In [39]:
# method 1
print( a * b) # element wise multiplication

# Method 2.
print(tf.multiply(a, b))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


### 4. tf.abs()
* Computes the absolute value of a tensor.

In [46]:
#  Absolute values of tensor c
tf.abs(c)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 2.,  8.,  9.,  6., 19.], dtype=float32)>

### 5. tf.math.accumulate_n(...)
* Returns the element-wise sum of a list of tensors.

In [49]:
# accumulate a and b
tf.math.accumulate_n([a, b])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

### 6. tf.math.acos()
* Computes acos of x element-wise.

In [57]:
x = tf.constant([1.0, -0.5, 3.4, 0.2, 0.0, -2], dtype = tf.float32)
tf.math.acos(x)

<tf.Tensor: shape=(6,), dtype=float32, numpy=
array([0.       , 2.0943952,       nan, 1.3694384, 1.5707964,       nan],
      dtype=float32)>

### 7. tf.math.acosh()
* Computes inverse hyperbolic cosine of x element-wise.

In [61]:
# acosh(c)
tf.math.acosh(c)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([      nan,       nan, 2.887271 , 2.4778888,       nan],
      dtype=float32)>

### 8. tf.math.add_n()
* Adds all input tensors element-wise.

In [64]:
tf.math.add_n([a, b])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

### 9. tf.math.angle()
* Returns the element-wise argument of a complex (or real) tensor.

In [67]:
# math.angle of vector c

tf.math.angle(c)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([3.1415927, 3.1415927, 0.       , 0.       , 3.1415927],
      dtype=float32)>

### 10. tf.argmax()
* Returns the index with the largest value across axes of a tensor.

In [74]:
# Largest element index
tf.argmax(a)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1], dtype=int64)>

### 11. tf.argmin()
* Returns the index with the smallest value across axes of a tensor.

In [75]:
# Smallest element index
tf.argmin(a)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 0], dtype=int64)>

### 12. tf.math.cumprod()
* Compute the cumulative product of the tensor x along axis.

In [78]:
tf.math.cumprod([a, b], 1)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 8]],

       [[1, 1],
        [1, 1]]])>

### 13. tf.math.cumsum()
* Compute the cumulative sum of the tensor x along axis.

In [79]:
tf.math.cumsum(a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 6]])>

### 14. tf.exp()
*  Computes exponential of x element-wise. 

In [80]:
tf.exp(c)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([1.3533528e-01, 3.3546262e-04, 8.1030840e+03, 4.0342880e+02,
       5.6027964e-09], dtype=float32)>

### 15. tf.floor() || ceil
* Returns element-wise largest integer not greater than x.

In [81]:
tf.floor(c)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ -2.,  -8.,   9.,   6., -19.], dtype=float32)>

### 16. tf.greater() || tf.less()
* Returns the truth value of (x > y) element-wise.

In [87]:
tf.greater(a, b, 1) # along the x-axis

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[False,  True],
       [ True,  True]])>

### 17. tf.greater_equal() || tf.less_equal()
* Returns the truth value of (x >= y) element-wise.

In [86]:
tf.greater_equal(a, b, 0) # along the y-axis

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

### 18. tf.math.is_finite() || is_inf()
* Returns which elements of x are finite.

In [98]:
tf.math.is_finite(c)

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([ True,  True,  True,  True,  True])>

### 19. tf.math.is_nan()
* Returns which elements of x are NaN.

In [95]:
tf.math.is_nan(c)

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([False, False, False, False, False])>

### 20. tf.maximum() || tf.mininum()
* Returns the max of x and y (i.e. x > y ? x : y) element-wise.

In [104]:
tf.maximum(b, a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

### 21. tf..math.not_equal() || tf.math.equal()
* Returns the truth value of (x != y) element-wise.

In [105]:
tf.math.not_equal(a, b)

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[False,  True],
       [ True,  True]])>

### 22. tf.pow()
*  Computes the power of one value to another.

In [116]:
tf.pow(a, 3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  8],
       [27, 64]])>

### 23. tf.negative()
* Computes numerical negative value element-wise.
* negate every element

In [111]:
tf.math.negative([a, b])
tf.math.negative(a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-1, -2],
       [-3, -4]])>

### 24. tf.math.round()
* Rounds the values of a tensor to the nearest integer, element-wise.

In [114]:
tf.math.round(tf.constant([2.5541, 2.65, 9.07, 8.9913]))

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([3., 3., 9., 9.], dtype=float32)>

### 25. tf.sqrt()
* Computes element-wise square root of the input tensor.

In [122]:
tf.math.sqrt(tf.constant([4, 9, 16, 25], dtype=tf.float32))

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2., 3., 4., 5.], dtype=float32)>

### 26. tf.square()
* Computes square of x element-wise.

In [123]:
tf.math.square(tf.constant([1,2,3,4,5,6]))

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36])>

### 27. tf.sort()
* Sorts a tensor

In [136]:
tf.sort(a,  direction='ASCENDING') 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

### More abouth tensor Math
* [Math](https://www.tensorflow.org/api_docs/python/tf/math)

## About Shapes
* **Shape**: The length (number of elements) of each of the axes of a tensor.
* **Rank**: Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
* **Axis** or **Dimension**: A particular dimension of a tensor.
* **Size**: The total number of items in the tensor, the product shape vector.

### 1. tf.shape()
* Returns a tensor containing the shape of the input tensor.


In [128]:
# Example
tf.shape(a)

## Or 
a.shape

TensorShape([2, 2])

### 2. tf.shape_n()
* Returns shape of tensors.

In [131]:
#  Example
tf.shape_n(a)


[<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2])>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([2])>]

## Reshaping a tensor
* tf.reshape(tensor, shape)
    * Reshapes a tensor.
    * When reshaping the tensor the elements of the product of the shape of the original tensor must be equal to the product of the shape of the new tensor
    

In [139]:
tensor_1d = tf.ones(18, dtype=tf.int32) # create a tensor of 18 1's
tensor_1d

<tf.Tensor: shape=(18,), dtype=int32, numpy=array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])>

### Resahping a tensors

In [140]:
tensor_2d = tf.reshape(tensor_1d, (2, -1)) 
tensor_2d

<tf.Tensor: shape=(2, 9), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])>

* The `-1`, tells tensorflow that reshape this tensor to 2d and fit all the elements


In [143]:
tensor = tf.reshape(tensor_1d, (3, -1)) 
tensor

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])>

In [144]:
tensor = tf.reshape(tensor_1d, (6, -1)) 
tensor

<tf.Tensor: shape=(6, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])>

In [145]:
tensor = tf.reshape(tensor_1d, (9, -1)) 
tensor

<tf.Tensor: shape=(9, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])>

In [146]:
tensor = tf.reshape(tensor_1d, (18, -1)) 
tensor

<tf.Tensor: shape=(18, 1), dtype=int32, numpy=
array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])>

In [147]:
tensor = tf.reshape(tensor_1d, (3, 6)) 
tensor

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])>

## Generating Tensors
* We can generate tensors filled with values the way we did it in numpy using the `ones`, `zeros`, `ones_like`, `zeros_like`, etc

### `tf.ones()`
* Creates a tensor with all elements set to one (1)

In [151]:
# generating a tf of ones and dtype = boolean
ones = tf.ones((3, 3), dtype=tf.bool)
print(ones)

# tensor of int one's
ones = tf.ones((3,4), dtype=tf.int16)
print(ones)


tf.Tensor(
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]], shape=(3, 3), dtype=bool)
tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int16)


### `tf.ones_like()`
* Creates a tensor of all ones that has the same shape as the input.

In [154]:
a = tf.Variable([[1, 2, 3, 4], [1, 5, 9, 0]])

ones = tf.ones_like(a)
ones

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1]])>

### `tf.zeros()`
* Creates a tensor with all elements set to zero.

In [155]:
# generating a tf of ones and dtype = boolean
zeros = tf.zeros((3, 3), dtype=tf.bool)
print(zeros)

# tensor of int one's
zeros = tf.zeros((3,4), dtype=tf.int16)
print(zeros)

tf.Tensor(
[[False False False]
 [False False False]
 [False False False]], shape=(3, 3), dtype=bool)
tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int16)


### `tf.zeros_like()`
* Creates a tensor with all elements set to zero.

In [156]:
a = tf.Variable([[1, 2, 3, 4], [1, 5, 9, 0]])
zeros = tf.zeros_like(a)
zeros

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]])>

### `tf.fill()`
* Creates a tensor filled with a scalar value.
    * ```
    tf.fill(
    dims, value, name=None
    )
    ```
* This method is the same as `numpy.full()`

In [158]:
tensorFill = tf.fill((2,3), 4)
tensorFill

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 4, 4],
       [4, 4, 4]])>

## 1. `tf.Variable()`
* Just like any `Tensor`, variables created with `Variable()` can be used as inputs to operations. Additionally, all the operators overloaded for the Tensor class are carried over to variables.

In [163]:
w = tf.Variable([[1.], [2.]])
w

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

## 2. `tf.constant()`
* Creates a constant tensor from a tensor-like object.

In [164]:
bool_t = tf.constant([True, False, False, False], dtype=tf.bool)
bool_t

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False, False, False])>