### `tf.bitwise()` 
* Operations for manipulating the binary representations of integers.
* [Read the Docs](https://www.tensorflow.org/api_docs/python/tf/bitwise)

In [1]:
import tensorflow as tf

In [8]:
A = tf.constant([True, True, True, False, True, False, False, True], dtype=tf.int32)
B = tf.constant([False, False, True,True, True, False, False, True], dtype=tf.int32)
A, B

(<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 1, 1, 0, 1, 0, 0, 1])>,
 <tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 0, 1, 1, 1, 0, 0, 1])>)

### 1. `bitwise_and()`
Elementwise computes the bitwise AND of x and y.
* Returns true if and only if both elements are true else false

In [9]:
tf.bitwise.bitwise_and(A, B)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 0, 1, 0, 1, 0, 0, 1])>

### 2. `bitwise_or()`
Elementwise computes the bitwise OR of x and y.
* Returns true if either of the elements are true else false.

In [10]:
tf.bitwise.bitwise_or(A, B)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 1, 1, 1, 1, 0, 0, 1])>

### 3. `bitwise_xor()`
Elementwise computes the bitwise XOR of x and y.
* Returns true if and only if one element becomes true else false

In [11]:
tf.bitwise.bitwise_xor(A, B)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 1, 0, 1, 0, 0, 0, 0])>

### 4. `invert()`
Invert (flip) each bit of supported types; for example, type uint8 value ``01010101`` becomes ``10101010``.

In [13]:
tf.bitwise.invert(A)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([-2, -2, -2, -1, -2, -1, -1, -2])>

### 5. `left_shift()`
Elementwise computes the bitwise left-shift of x and y.

In [14]:
tf.bitwise.left_shift(A, B)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 1, 2, 0, 2, 0, 0, 2])>

### 6. `right_shift()`
Elementwise computes the bitwise right-shift of x and y.

In [15]:
tf.bitwise.right_shift(A, B)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 1, 0, 0, 0, 0, 0, 0])>

That's all about bitwise operations on tensors.