### Installation

In [1]:
pip install -q tensorflow tensorflow-datasets

#### Imports

In [2]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
from tensorflow import keras
import tensorflow_datasets as tfds

### Checking datasets

In [3]:
print(tfds.list_builders())

['abstract_reasoning', 'accentdb', 'aeslc', 'aflw2k3d', 'ag_news_subset', 'ai2_arc', 'ai2_arc_with_ir', 'amazon_us_reviews', 'anli', 'arc', 'bair_robot_pushing_small', 'bccd', 'beans', 'big_patent', 'bigearthnet', 'billsum', 'binarized_mnist', 'binary_alpha_digits', 'blimp', 'bool_q', 'c4', 'caltech101', 'caltech_birds2010', 'caltech_birds2011', 'cars196', 'cassava', 'cats_vs_dogs', 'celeb_a', 'celeb_a_hq', 'cfq', 'chexpert', 'cifar10', 'cifar100', 'cifar10_1', 'cifar10_corrupted', 'citrus_leaves', 'cityscapes', 'civil_comments', 'clevr', 'clic', 'clinc_oos', 'cmaterdb', 'cnn_dailymail', 'coco', 'coco_captions', 'coil100', 'colorectal_histology', 'colorectal_histology_large', 'common_voice', 'coqa', 'cos_e', 'cosmos_qa', 'covid19sum', 'crema_d', 'curated_breast_imaging_ddsm', 'cycle_gan', 'deep_weeds', 'definite_pronoun_resolution', 'dementiabank', 'diabetic_retinopathy_detection', 'div2k', 'dmlab', 'downsampled_imagenet', 'dsprites', 'dtd', 'duke_ultrasound', 'emnist', 'eraser_multi_r

### Getting data Infomation

In [4]:
builder = tfds.builder('rock_paper_scissors')
info = builder.info
print(info)

tfds.core.DatasetInfo(
    name='rock_paper_scissors',
    version=3.0.0,
    description='Images of hands playing rock, paper, scissor game.',
    homepage='http://laurencemoroney.com/rock-paper-scissors-dataset',
    features=FeaturesDict({
        'image': Image(shape=(300, 300, 3), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=3),
    }),
    total_num_examples=2892,
    splits={
        'test': 372,
        'train': 2520,
    },
    supervised_keys=('image', 'label'),
    citation="""@ONLINE {rps,
    author = "Laurence Moroney",
    title = "Rock, Paper, Scissors Dataset",
    month = "feb",
    year = "2019",
    url = "http://laurencemoroney.com/rock-paper-scissors-dataset"
    }""",
    redistribution_info=,
)



### Data Preparation

In [5]:
train = tfds.load(name='rock_paper_scissors', split="train")
test = tfds.load(name='rock_paper_scissors', split='test')

### Iterating over data
> To iterate over a tensorflow dataset we do it as follows

In [6]:
for data in train:
  print(data['image'], data['label'])
  break

tf.Tensor(
[[[254 254 254]
  [253 253 253]
  [254 254 254]
  ...
  [251 251 251]
  [250 250 250]
  [250 250 250]]

 [[254 254 254]
  [254 254 254]
  [253 253 253]
  ...
  [250 250 250]
  [251 251 251]
  [249 249 249]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [251 251 251]
  [250 250 250]
  [252 252 252]]

 ...

 [[252 252 252]
  [251 251 251]
  [252 252 252]
  ...
  [247 247 247]
  [249 249 249]
  [248 248 248]]

 [[253 253 253]
  [253 253 253]
  [251 251 251]
  ...
  [248 248 248]
  [248 248 248]
  [248 248 248]]

 [[252 252 252]
  [253 253 253]
  [252 252 252]
  ...
  [248 248 248]
  [247 247 247]
  [250 250 250]]], shape=(300, 300, 3), dtype=uint8) tf.Tensor(2, shape=(), dtype=int64)


### Creating a Numpy data
> We are going to scale our data and convert it to a nummpy array

In [7]:
train_images = np.array([data['image'].numpy()/255 for data in train])
train_labels =np.array([data['label'].numpy() for data in train])
test_image = np.array([data['image'].numpy()/255   for data in test])
test_labels = np.array([data['label'].numpy() for data in test])

In [8]:
train_images[0]

array([[[0.99607843, 0.99607843, 0.99607843],
        [0.99215686, 0.99215686, 0.99215686],
        [0.99607843, 0.99607843, 0.99607843],
        ...,
        [0.98431373, 0.98431373, 0.98431373],
        [0.98039216, 0.98039216, 0.98039216],
        [0.98039216, 0.98039216, 0.98039216]],

       [[0.99607843, 0.99607843, 0.99607843],
        [0.99607843, 0.99607843, 0.99607843],
        [0.99215686, 0.99215686, 0.99215686],
        ...,
        [0.98039216, 0.98039216, 0.98039216],
        [0.98431373, 0.98431373, 0.98431373],
        [0.97647059, 0.97647059, 0.97647059]],

       [[0.99607843, 0.99607843, 0.99607843],
        [0.99607843, 0.99607843, 0.99607843],
        [0.99607843, 0.99607843, 0.99607843],
        ...,
        [0.98431373, 0.98431373, 0.98431373],
        [0.98039216, 0.98039216, 0.98039216],
        [0.98823529, 0.98823529, 0.98823529]],

       ...,

       [[0.98823529, 0.98823529, 0.98823529],
        [0.98431373, 0.98431373, 0.98431373],
        [0.98823529, 0

### Class Names
0 - Rock

1 - Paper

2 - Scissors

In [9]:
class_names = np.array(["rock", "paper", "scissor"])

### Creating a NN

In [10]:
input_shape = train_images[0].shape
input_shape

(300, 300, 3)

In [11]:

model = keras.Sequential([
    keras.layers.Conv2D(32, (3, 3), input_shape=input_shape, activation='relu'),
    keras.layers.MaxPool2D((3,3)) ,
    keras.layers.Conv2D(64, (2, 2), activation='relu'),
    keras.layers.MaxPool2D((2,2)),
    keras.layers.Conv2D(64, (2, 2), activation='relu'),
    keras.layers.MaxPool2D((2,2)),
    keras.layers.Flatten(),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(3, activation='softmax')
])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 298, 298, 32)      896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 99, 99, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 98, 98, 64)        8256      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 49, 49, 64)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 48, 48, 64)        16448     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 24, 24, 64)        0         
_________________________________________________________________
flatten (Flatten)            (None, 36864)             0

### Combiling the Model

In [12]:
model.compile(
    optimizer = keras.optimizers.Adam(learning_rate=.0001),
    metrics=["accuracy"],
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True)
)

### Fitting the ModeL

In [13]:
EPOCHS = 5
BATCH_SIZE = 4
VALIDATION_SET = (test_image, test_labels)
history = model.fit(train_images, train_labels, epochs=EPOCHS, validation_data=VALIDATION_SET, batch_size=BATCH_SIZE)

Epoch 1/5
630/630 [==============================] - 41s 13ms/step - loss: 0.7952 - accuracy: 0.6217 - val_loss: 0.3887 - val_accuracy: 0.8360
Epoch 2/5
630/630 [==============================] - 6s 10ms/step - loss: 0.0271 - accuracy: 0.9946 - val_loss: 0.4615 - val_accuracy: 0.8763
Epoch 3/5
630/630 [==============================] - 6s 10ms/step - loss: 0.0055 - accuracy: 0.9992 - val_loss: 0.5403 - val_accuracy: 0.8629
Epoch 4/5
630/630 [==============================] - 6s 9ms/step - loss: 0.0014 - accuracy: 1.0000 - val_loss: 0.6153 - val_accuracy: 0.8468
Epoch 5/5
630/630 [==============================] - 6s 10ms/step - loss: 3.5554e-04 - accuracy: 1.0000 - val_loss: 0.6667 - val_accuracy: 0.8468


### Model Evaluation Conclusion
Our model is performing perfect. The loss on the train_set is almost 0 as well as the validation loss. The accuracy on the train set is `100%` compared to `83%` accuracy on the test set.

> The model is just overtraining but giving us good results on the validation set.

### Making Predictions


In [15]:
predictions = model.predict(test_image[:10])
for i, j in zip(predictions, test_labels[:10]):
  print(class_names[np.argmax(i)],"-------->", class_names[j])

scissor --------> scissor
paper --------> paper
paper --------> scissor
rock --------> rock
rock --------> rock
rock --------> rock
paper --------> paper
paper --------> paper
scissor --------> scissor
paper --------> paper


### Tunning Hyper Parameters -- Keras-Tunner
* [Docs](https://www.tensorflow.org/tutorials/keras/keras_tuner)


### Installation

In [16]:
pip install -q -U keras-tuner

     |████████████████████████████████| 71kB 8.8MB/s 


### Importing

In [6]:
import kerastuner as kt

In [7]:
def model_builder(hp):

  model = keras.Sequential()
  #   we want the model to find the best unit and the activation function for the first layer for us
  model.add(keras.layers.Conv2D(hp.Int('units',  min_value=32, max_value=512, step=32),(3, 3), 
                                input_shape=input_shape, activation=hp.Choice('activation-fn',values=['relu', 'sgd'])))
  
  model.add(keras.layers.MaxPool2D((3,3)))
  model.add(keras.layers.Conv2D(64, (2, 2), activation='relu'))
  model.add(keras.layers.MaxPool2D((2,2)))
  model.add(keras.layers.Conv2D(64, (2, 2), activation='relu'))
  model.add(keras.layers.MaxPool2D((2,2)))
  model.add(keras.layers.Flatten())
  model.add(keras.layers.Dense(64, activation='relu'))
  model.add(keras.layers.Dense(32, activation='relu'))
  model.add(keras.layers.Dense(3, activation='softmax'))
  model.compile(optimizer=keras.optimizers.Adam(learning_rate=hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4])),
                loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                metrics=['accuracy'])
  return model

In [12]:
tuner = kt.Hyperband(model_builder,
                     objective='val_accuracy',
                     max_epochs=10,
                     )

INFO:tensorflow:Reloading Oracle from existing project ./untitled_project/oracle.json


INFO:tensorflow:Reloading Oracle from existing project ./untitled_project/oracle.json


In [ ]:
tuner.search(train_images, train_labels, validation_data=VALIDATION_SET, epochs=EPOCHS, batch_size=BATCH_SIZE)

Trial 1 Complete [00h 01m 13s]
val_accuracy: 0.8951612710952759

Best val_accuracy So Far: 0.8951612710952759
Total elapsed time: 00h 01m 13s

Search: Running Trial #2

Hyperparameter    |Value             |Best Value So Far 
units             |480               |192               
activation-fn     |relu              |relu              
learning_rate     |0.0001            |0.0001            
tuner/epochs      |2                 |2                 
tuner/initial_e...|0                 |0                 
tuner/bracket     |2                 |2                 
tuner/round       |0                 |0                 

Epoch 1/2
  6/630 [..............................] - ETA: 41s - loss: 1.0874 - accuracy: 0.4917WARNING:tensorflow:Callback method `on_train_batch_end` is slow compared to the batch time (batch time: 0.0117s vs `on_train_batch_end` time: 0.0462s). Check your callbacks.


630/630 [==============================] - ETA: 0s - loss: 0.7553 - accuracy: 0.6167

> That's basically how the `kerastunner` works