### `tf.strings()`
These are operations to work with string tensors.
* [Docs](https://www.tensorflow.org/api_docs/python/tf/strings/as_string)
In this notebook we are going to cover the most usefull and basic string functions from the `tf.strings()`

In [1]:
import tensorflow as tf

### 1. ``as_string(...)``
Converts each entry in the given tensor to strings.
* The input must be of type, int, float, bool, ... 

In [4]:
A = tf.Variable([4, 5, 6, 7])
A_string = tf.strings.as_string(A,)
A_string

<tf.Tensor: shape=(4,), dtype=string, numpy=array([b'4', b'5', b'6', b'7'], dtype=object)>

In [ ]:
### 2. ``format(...)``
Converts each entry in the given tensor to strings.
* The input must be of type, int, float, bool, ... 

### 3. ``join(...)``
Perform element-wise concatenation of a list of string tensors.

In [13]:
tf.strings.join(["This", "is", "a", "boy"], separator=" ")

<tf.Tensor: shape=(), dtype=string, numpy=b'This is a boy'>

### 4. ``lenght(...)``
Returns the lenght of the string

In [16]:
A = tf.Variable(["This is a ", "This is a ", "This is a "])
B = tf.Variable(["boy", "girl", "apple"])

tf.strings.length(A), tf.strings.length(B)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 5])>)

### 5. ``lower(...)``
Converts the string to lowercase.

In [17]:
A = tf.Variable(["This is a ", "This is a ", "This is a "])
tf.strings.lower(A)

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'this is a ', b'this is a ', b'this is a '], dtype=object)>

### 6. ``ngrams(...)``
Create a tensor of n-grams based on data.

In [21]:
A = tf.Variable([str("The weather was very cold that noone could go out for a date.").split()])
tf.strings.ngrams(A, 3)

<tf.Tensor: shape=(1, 11), dtype=string, numpy=
array([[b'The weather was', b'weather was very', b'was very cold',
        b'very cold that', b'cold that noone', b'that noone could',
        b'noone could go', b'could go out', b'go out for', b'out for a',
        b'for a date.']], dtype=object)>

### 7. ``reduce_join(...)``
Join the strings in one long string along an axis.

In [26]:
tf.strings.reduce_join([
    ["this", "is", "a", "boy."],
    ["His", "name", "is", "jonh"]
], separator=" ").numpy()

b'this is a boy. His name is jonh'

### 8. ``regex_full_match(...)``

Matches the given list of strings with a regular expression and returns true if it matchs.

In [33]:
tf.strings.regex_full_match(["This", "is", "me", "1234"], pattern=r'^[a-z]+')

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([False,  True,  True, False])>

### 9. ``regex_replace(...)``
 Replace elements of input matching regex pattern with rewrite.

In [38]:
tf.strings.regex_replace(["This", "is", "me", "1234"], r'^[a-z]+', "1234")

<tf.Tensor: shape=(4,), dtype=string, numpy=array([b'This', b'1234', b'1234', b'1234'], dtype=object)>

### 10. ``strip(...)``
- Removes trailing white spaces. This method is simmilar to the python string method `strip()`

In [39]:
tf.strings.strip(["This ", " is ", " me ", " 1234"])

<tf.Tensor: shape=(4,), dtype=string, numpy=array([b'This', b'is', b'me', b'1234'], dtype=object)>

### 11. ``split(...)``
Split elements of input based on sep into a RaggedTensor.

In [42]:
tf.strings.split(["This is a long string which will be spitted by a space."], sep=" ")

<tf.RaggedTensor [[b'This', b'is', b'a', b'long', b'string', b'which', b'will', b'be', b'spitted', b'by', b'a', b'space.']]>

### 12. ``substr(...)``
Extract a string based on index and length from another string.

In [46]:
tf.strings.substr(["hello world"], pos=0, len=5).numpy()

array([b'hello'], dtype=object)

### 13. ``upper(...)``
Convert the given string to uppercase characters.

In [47]:
tf.strings.upper(["Hello world"]).numpy()

array([b'HELLO WORLD'], dtype=object)

### 14. ``to_number(...)``
Convert a given string to a number.

In [49]:
tf.strings.to_number([str(i) for i in range(10)], out_type="int32").numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> These are the most commonly used tensorflow string functions for more read the [docs](https://www.tensorflow.org/api_docs/python/tf/strings)